CREATE TABLE user (
    id INT NOT NULL AUTO_INCREMENT,
    email VARCHAR(75) NOT NULL UNIQUE,
    password VARCHAR(128) DEFAULT NULL,
    nick VARCHAR(75) NOT NULL UNIQUE,
    location VARCHAR(75) DEFAULT NULL,
    cellphone VARCHAR(70) DEFAULT NULL,
    piclink VARCHAR(512) DEFAULT NULL,
    PRIMARY KEY (id)
);

